### ISSUE TITLE
enumerate(fn)[:3] throws error

### ISSUE THREAD

**Issue by jpalaciose** [ajansen-tub/pyomac#5]
https://github.com/ajansen-tub/pyomac/blob/37ed5d13db57a2468dc89885bfbf5b9223e992ed/examples/bridge_example.py#L35

I think it should be enumerate(fn[:3]), shouldn't be?

**Comment by runlevel0** [comment]
Thank you for your bugreport.
I've added a fix in commit 818a665 along with a change to use the newer implementation of SSI.
Can you verify, if this fixes the issue for you?

Additionally, another place for examples is the documentation at https://pyomac.readthedocs.io/en/latest/

**Comment by jpalaciose** [comment]
Thanks for the repository and fixing the bug.
I like the Idea of using a new parameter 'modes_to_show', but I think "np.sort(fn[-1])" should be "np.sort(fn,-1)" and the same for  argsort.
Also, I opted for using "ssi_cov" function of the old version (deprecated) since it throws better results for my signals, despite longer running time.

**Comment by runlevel0** [comment]
Sorry, it took me a while to come around this again.
Thank you for your comments.
I assume, you are talking about lines 46 and 47:
```python
        fn_plot = np.sort(fn[-1])
        ms_plot = ms[-1][np.argsort(fn[-1]), :]
```
When using the `ssi_cov_poles` method, lists of frequencies, damping and modeshapes are returned, each containing modal results for all the SSI model orders. So, `fn[-1]` and `ms[-1]` only take the results from the last (that is the highest) model order.
Or am I missing something?

It is interesting to hear that the `ssi_cov` function yields better results. What makes these results better for you?

**Comment by jpalaciose** [comment]
Thanks for the explanation, that makes sense. 

When plotting the stabilization diagram I got this one with the previous ssi_cov:
![image](https://user-images.githubusercontent.com/72670288/155168931-4b5d8757-bc9b-4837-bd3a-2d505575f51d.png)

With the new implementation I got this one:
![image](https://user-images.githubusercontent.com/72670288/155170320-949afaad-b4a4-466b-84f8-6481420a2abf.png)
They are different diagrams but they seems to throw the same frequencies. So, they yields same results. Sorry for the misunderstanding.

**Comment by runlevel0** [comment]
Thank you for showing your plots.
They are indeed different in their form of representing information.

The newer and faster `ssi_cov_poles` requires explicit postprocessing, i.e. [Clustering](https://pyomac.readthedocs.io/en/latest/clustering.html) of the results.
The older and slower `ssi_cov` already included some postprocessing.

Thank you for testing our package. We are happy for every user!
If you care to share: What would be the TOP 3 things that you would need or wish from the package?

**Comment by jpalaciose** [comment]
Well I like the fact that I can compare my ssi results with fdd method.
I wish pyomac package could also plot the modeshapes in 3D. But I managed to code for that. 
Let me share:

phi = np.loadtxt(f)

phi[0] = x+phi[0]
phi[1] = y+phi[1]
phi[2] = z+phi[2]

fig = plt.figure(figsize=(10,10))
ax = fig.add_subplot(111,projection='3d')
ax.set_title('Z'); ax.set_xlabel('X'); ax.set_ylabel('   Y')
ax.plot_trisurf([5,17,17,5],[-4,-4,8,8],[-6,-6,6,6],alpha=0.0)
ax.plot_trisurf([5,17,17,5],[-4,-4,8,8],[0,0,0,0], linewidth=0.0, antialiased=True,cmap='gray',alpha=0.1,edgecolor='k',vmin=0,vmax=0)

for c in cnx:
    c = np.append(c,c[0])
    ax.plot(x[c],y[c],z[c],'ko:',lw=0.8,markersize=2.0)

ax.plot_trisurf(phi[0], phi[1], phi[2], triangles=cnx, linewidth=0.6, antialiased=True,cmap='Greys',alpha=0.6,edgecolor='k',vmin=1,vmax=1)
ax.view_init(elev=90,azim=270)
plt.tight_layout()
plt.savefig('LaTex/%s_plan.pdf'%f[:-4],dpi=300)
ax.view_init(elev=0,azim=270)
plt.tight_layout()
plt.savefig('LaTex/%s_elev.pdf'%f[:-4],dpi=300)

![image](https://user-images.githubusercontent.com/72670288/155391669-f190cd34-56fc-41f5-bbc5-c2a987bc1500.png)


Finally, I like the previous stabilization diagram or maybe I'm not using the package properly to plot with the current version.
